import { AlertCircle, BarChart3, Camera, CarFront, ClipboardList, Clock3, MapPin, PackageOpen, PiggyBank, Scale, UserRoundCheck, Wheat } from "lucide-react";

function IntegratorMockup() { return <div className="roleMock integratorMock"><div className="roleMockTop"><span>PAINEL DA INTEGRADORA</span><b>Operação • Hoje</b></div><div className="integratorMetrics"><div><small>Granjas ativas</small><strong>28</strong></div><div><small>Precisam de visita</small><strong className="attention">04</strong></div><div><small>Lotes ativos</small><strong>32</strong></div></div><div className="farmRows"><p><span><i className="good"/> Granja Boa Vista</span><em>Dentro do padrão</em></p><p><span><i className="warn"/> Granja Horizonte</span><em>Revisar mortalidade</em></p><p><span><i className="visit"/> Granja Esperança</span><em>Visita recomendada</em></p></div><div className="mockLegend"><BarChart3 size={15}/> Indicadores consolidados em uma única visão</div></div> }
function TechnicianMockup() { return <div className="roleMock technicianMock"><div className="routeTop"><small>ROTA TÉCNICA</small><strong>Prioridades de hoje</strong></div><div className="mapGrid" aria-label="Mapa ilustrativo com rota técnica entre granjas"><div className="mapField fieldOne"/><div className="mapField fieldTwo"/><div className="mapField fieldThree"/><div className="mapRoad roadOne"/><div className="mapRoad roadTwo"/><div className="mapRoad roadThree"/><div className="routeLine routeOne"/><div className="routeLine routeTwo"/><div className="routeLine routeThree"/><span className="mapLabel labelOne">Linha Horizonte</span><span className="mapLabel labelTwo">Estrada Rural 12</span><span className="pin p1"><MapPin/></span><span className="pin p2"><MapPin/></span><span className="pin p3"><MapPin/></span><span className="mapCar"><CarFront/><em>Em rota</em></span></div><div className="visitList"><p><span>01</span><b>Granja Horizonte<small>Mortalidade requer atenção</small></b><em>08:30</em></p><p><span>02</span><b>Granja Santa Clara<small>Acompanhar ração</small></b><em>10:15</em></p></div></div> }
function ProducerMockup() { return <div className="phoneFrame"><div className="phoneBar"><span>09:41</span><i/></div><div className="phoneContent"><small>LOTE 2026-018</small><h4>Registro diário</h4><div className="phoneStat"><PiggyBank/><p><span>Animais vivos</span><strong>28.450</strong></p></div><div className="quickActions"><span><Scale/>Mortalidade</span><span><Wheat/>Ração</span><span><Camera/>Ocorrência</span><span><ClipboardList/>Relatório</span></div><button>Concluir registro</button><em>Última sincronização: agora</em></div></div> }

export function RolePanels() {
  return <section className="rolePanels" id="recursos">
    <div className="roleSection integrator"><div className="roleSectionInner"><div className="roleText" data-reveal><span className="numberTag">01 · INTEGRADORA</span><h2>Visão completa sem perder o detalhe do campo</h2><p>Encontre granjas críticas, acompanhe lotes, mortalidade e vínculos entre técnicos e produtores em um painel operacional consolidado.</p><ul><li><AlertCircle/> Granjas que precisam de atenção</li><li><UserRoundCheck/> Gestão de técnicos e produtores</li><li><BarChart3/> Indicadores e relatórios consolidados</li></ul></div><IntegratorMockup/></div></div>
    <div className="roleSection technician"><div className="roleSectionInner reverse"><TechnicianMockup/><div className="roleText" data-reveal><span className="numberTag blue">02 · TÉCNICO</span><h2>O técnico sabe onde precisa estar antes mesmo de sair para o campo</h2><p>O GranjaFlow ajuda a organizar prioridades, consultar históricos e acompanhar as granjas vinculadas, sem substituir a avaliação técnica.</p><ul><li><MapPin/> Priorização e acompanhamento de visitas</li><li><Clock3/> Histórico por granja e lote</li><li><Camera/> Ocorrências, fotos, GTA e relatórios</li></ul></div></div></div>
    <div className="roleSection producer"><div className="roleSectionInner"><div className="roleText" data-reveal><span className="numberTag yellow">03 · PRODUTOR</span><h2>Registrar o dia da granja deve ser simples, rápido e confiável</h2><p>Uma experiência pensada para o celular: mortalidade por sexo, controle interno, causas, ração, ocorrências, fotos e vídeos.</p><ul><li><Scale/> Mortalidade, machos, fêmeas e mossa</li><li><Wheat/> Pedidos, entregas e dias de ração</li><li><PackageOpen/> Lote, ocorrências e relatórios</li></ul></div><ProducerMockup/></div></div>
  </section>;
}
