import type { Metadata } from "next";
import LegalLayout from "../legal-layout";

export const metadata: Metadata = { title: "Política de Privacidade e LGPD | GranjaFlow", description: "Como o site público do GranjaFlow trata dados pessoais e respeita a LGPD." };

export default function PrivacyPage() {
  return <LegalLayout title="Política de Privacidade e LGPD" intro="Esta política explica, de forma transparente, como os dados pessoais podem ser tratados no site público do GranjaFlow.">
    <section><h2>1. Quem é responsável</h2><p>O site GranjaFlow é mantido pela FFR do Brasil Technology. Para assuntos relacionados à privacidade, solicitações de titulares ou dúvidas sobre esta política, entre em contato pelo e-mail <a href="mailto:contato@granjaflow.com.br">contato@granjaflow.com.br</a>.</p></section>
    <section><h2>2. A quem esta política se aplica</h2><p>Esta política se aplica à navegação no site institucional disponível em granjaflow.com.br. O aplicativo acessado em app.granjaflow.com.br possui contexto operacional próprio e pode adotar documentos específicos conforme a contratação, os perfis de acesso e o tratamento realizado em cada operação.</p></section>
    <section><h2>3. Dados que podem ser tratados</h2><p>O site público não exige cadastro e não possui formulário próprio nesta versão. Ainda assim, dados técnicos mínimos podem ser processados pela infraestrutura de hospedagem para entregar a página com segurança, como endereço IP, data e hora de acesso, tipo de navegador, dispositivo, página solicitada e registros técnicos de segurança.</p><p>Quando você escolhe falar pelo WhatsApp ou enviar um e-mail, o tratamento passa a ocorrer também nos serviços escolhidos por você. As informações enviadas podem incluir nome, telefone, e-mail, empresa, propriedade, interesse comercial e o conteúdo da conversa.</p></section>
    <section><h2>4. Finalidades e bases legais</h2><ul><li>Disponibilizar o site, prevenir abuso e manter a segurança, com base no legítimo interesse e no cumprimento de obrigações legais.</li><li>Responder contatos e solicitações comerciais, com base em procedimentos preliminares relacionados a contrato ou no legítimo interesse.</li><li>Cumprir determinações legais, regulatórias ou de autoridades competentes.</li><li>Defender direitos em processos judiciais, administrativos ou arbitrais.</li></ul></section>
    <section><h2>5. Compartilhamento</h2><p>Dados podem ser processados por fornecedores estritamente necessários à hospedagem, segurança, comunicação e operação técnica. Ao abrir WhatsApp, e-mail ou sites de terceiros, você passa a interagir com serviços que possuem políticas próprias. O GranjaFlow não vende dados pessoais.</p></section>
    <section><h2>6. Transferência internacional</h2><p>Alguns fornecedores de tecnologia podem operar infraestrutura fora do Brasil. Quando aplicável, o tratamento deve observar mecanismos admitidos pela LGPD e medidas adequadas de proteção.</p></section>
    <section><h2>7. Retenção e descarte</h2><p>Os dados são mantidos apenas pelo período necessário para atender às finalidades informadas, cumprir obrigações legais, resguardar direitos ou manter registros de segurança. Encerrado o período aplicável, os dados devem ser eliminados ou anonimizados, salvo quando a conservação for autorizada ou exigida por lei.</p></section>
    <section><h2>8. Segurança</h2><p>São adotadas medidas técnicas e administrativas proporcionais ao contexto para reduzir riscos de acesso indevido, perda, alteração ou divulgação não autorizada. Nenhum ambiente digital é totalmente isento de risco. Em caso de incidente relevante, serão observadas as obrigações legais aplicáveis.</p></section>
    <section><h2>9. Direitos do titular</h2><p>Nos limites da LGPD, você pode solicitar confirmação de tratamento, acesso, correção, anonimização, bloqueio, eliminação, portabilidade, informação sobre compartilhamento, revisão de decisões automatizadas, revogação de consentimento e oposição quando cabível. A identidade do solicitante poderá ser confirmada para evitar fraude ou exposição indevida.</p></section>
    <section><h2>10. Como exercer seus direitos</h2><p>As solicitações podem ser enviadas para <a href="mailto:contato@granjaflow.com.br">contato@granjaflow.com.br</a>. Informe o direito que deseja exercer e dados suficientes para localizar a interação. A resposta observará os prazos legais, e pedidos excessivos, impossíveis ou que afetem direitos de terceiros poderão ser tratados conforme a legislação.</p></section>
    <section><h2>11. Cookies e armazenamento local</h2><p>O site utiliza armazenamento local essencial para lembrar a preferência exibida no aviso de cookies. Nesta versão não são ativados cookies de publicidade, perfilamento ou análise comportamental. Os detalhes estão na <a href="/cookies">Política de Cookies</a>.</p></section>
    <section><h2>12. Decisões automatizadas</h2><p>O site institucional não realiza decisões exclusivamente automatizadas que produzam efeitos jurídicos ou afetem significativamente o visitante.</p></section>
    <section><h2>13. Crianças e adolescentes</h2><p>O site é destinado a contatos profissionais e comerciais. Não buscamos coletar intencionalmente dados de crianças ou adolescentes. Se identificar envio inadequado, solicite a análise e eventual remoção pelos canais informados.</p></section>
    <section><h2>14. Alterações desta política</h2><p>Esta política pode ser atualizada para refletir mudanças legais, técnicas ou operacionais. A versão vigente será sempre indicada nesta página com sua data de atualização.</p></section>
    <section><h2>15. Autoridade competente</h2><p>Além de falar conosco, o titular pode apresentar petição à Autoridade Nacional de Proteção de Dados, conforme as condições previstas na legislação.</p></section>
  </LegalLayout>;
}
